// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rasterize_polygons
Rcpp::S4 rasterize_polygons(Rcpp::S4& raster, Rcpp::List& polygons, Rcpp::NumericVector& field_values, std::string fun, double background);
RcppExport SEXP fasterize_rasterize_polygons(SEXP rasterSEXP, SEXP polygonsSEXP, SEXP field_valuesSEXP, SEXP funSEXP, SEXP backgroundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4& >::type raster(rasterSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type polygons(polygonsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type field_values(field_valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type fun(funSEXP);
    Rcpp::traits::input_parameter< double >::type background(backgroundSEXP);
    rcpp_result_gen = Rcpp::wrap(rasterize_polygons(raster, polygons, field_values, fun, background));
    return rcpp_result_gen;
END_RCPP
}
