# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rasterize_polygons <- function(polygons, field_values, raster_info, background) {
    .Call('fasterize_rasterize_polygons', PACKAGE = 'fasterize', polygons, field_values, raster_info, background)
}

