# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fasterize_cpp <- function(sf, raster, field = NULL, fun = "last", background = NA_real_, by = NULL) {
    .Call('_fasterize_fasterize_cpp', PACKAGE = 'fasterize', sf, raster, field, fun, background, by)
}

