# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rasterize_polygons <- function(raster, polygons, field_values, background) {
    .Call('fasterize_rasterize_polygons', PACKAGE = 'fasterize', raster, polygons, field_values, background)
}

